In [3]:
s = set(['aa', 'bb', 'aa'])
print(s)

{'aa', 'bb'}


In [6]:
s1 = set('abcdabcd')
print(s1)

{'abcdabcd'}


In [8]:
s2 = set(['abcdabcd'])
print(s1)

{'abcdabcd'}


In [26]:
import pandas as pd
import random as rnd
import numpy as np
from scipy.stats import pearsonr
import pickle

In [94]:
a, b = -.1, -10
x = np.random.rand(100)
y = a*x+b
# print(x)
# print(y)

In [95]:
np.corrcoef(y,x)

array([[ 1., -1.],
       [-1.,  1.]])

In [96]:
pearsonr(y,x)

PearsonRResult(statistic=-1.0, pvalue=0.0)

In [112]:
from scipy.signal import correlate

In [115]:
N=3
x = np.random.rand(N)*np.pi*2
v1 = np.ones(2*N).reshape(2,N)
v2 = np.ones(2*N).reshape(2,N)
print(v1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [116]:
correlate(v1, v2)

array([[1., 2., 3., 2., 1.],
       [2., 4., 6., 4., 2.],
       [1., 2., 3., 2., 1.]])

In [21]:
def it(N=10):
    for i in range(N):
        yield i

In [33]:
x=it()
for i in range(10):
    val = x.__next__()
    if i > 5:
        jt = it
        break
    print(val)

with open('x.pickle', 'w') as handle: 
    pickle.dump(str(x), handle, protocol=pickle.HIGHEST_PROTOCOL)о

0
1
2
3
4
5


TypeError: write() argument must be str, not bytes

In [25]:
for i in range(2):
    try:    
        val = x.__next__()
    except:
        break
    print(val)

In [41]:
warn_level = True

def print_level(*args, **kwargs):
    
    def wrapper(func):
        func(kwargs['warn'])
        
    return wrapper

@print_level(warn = warn_level)
def warned_you(warn):
    if warn:
        print('I warned you')


I warned you


In [50]:
import functools
def log_decorator(log_enabled):
    def actual_decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            if log_enabled:
                print("Calling Function: " + func.__name__)
            return func(*args, **kwargs)
        return wrapper
    return actual_decorator

In [59]:
enable_log=True
@log_decorator(enable_log)
def f(x):
    return x+1

@log_decorator(enable_log)
def g(x):
    return x+1

In [65]:
f(4)
g(100)

# need to change it in the definition:
enable_log=False
f(4)
g(100)

Calling Function: f
Calling Function: g
Calling Function: f
Calling Function: g


101